# port config for gateway
server:
    port: 5000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
    data:
        mongodb:
                uri: REPLACED
                database: tax-estimate
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    output:
        ansi:
            enabled: ALWAYS