# port config for gateway
server:
    port: 8080

spring:
    data:
        mongodb:
                uri: ${MONGO_URI}
                database: tax-estimate
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    output:
        ansi:
            enabled: ALWAYS